### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by startedourmission** [startedourmission/ITC_2023_2_WirleesNetwork_4#1]
아이디어 회의 및 피드백

**Comment by wmsgur8679** [comment]
택배 도난방지
1. 기반 : 라즈베리파이, 아두이노
2.센서 : 카메라, 움직임 감지, 무게 감지
3. 언어 : python
개발 목적 : 택배도둑이 CCTV가 없는 집에 택배의 도난을 방지하기 위해서
집 앞 문에 움직임 감지센서로 움직을 감지하고 무게 감지 센서에 택배가 놓이면 사진을 찰영한다.
무게 감지 센서에서 택배가 사라질 떄 촬영을 한다.
이떄 촬영된 사진은 사용자의 핸드폰(메신저등)으로 전송돼 택배가 잘왔음을 확인하다.

**Comment by startedourmission** [comment]
@wmsgur8679 구체적인 센서의 모델명과 어떤 방식으로 구할 수 있는지 궁금합니다.

**Comment by startedourmission** [comment]
> @wmsgur8679 구체적인 센서의 모델명과 어떤 방식으로 구할 수 있는지 궁금합니다.

추가로 기존에 비슷한 시스템이 있는지, 있으면 어떻게 구성되어있는지 이미지가 있으면 좋을 것 같습니다.

**Comment by startedourmission** [comment]
@WithTheMoonRabbit 온습도, 공기질, GPS외에도 추가적으로 고려할만한 센서가 있는지 궁금합니다.

**Comment by startedourmission** [comment]
@fromsehyeon 프로젝트 기간 내에 어떠한 자동화 기능들을 구현할 생각인지 구체적인 스케일이 궁금합니다.
